foods = {
  "menustration": [
    { "food": "Spinach", "nutrients": ["iron-rich", "magnesium"], "type": "fresh" },
    { "food": "Kale", "nutrients": ["iron-rich", "vitamin K"], "type": "fresh" },
    { "food": "Broccoli", "nutrients": ["vitamin C", "fiber"], "type": "fresh" },
    { "food": "Lentils", "nutrients": ["iron-rich", "protein", "fiber"], "type": "store cupboard" },
    { "food": "Chickpeas", "nutrients": ["protein", "fiber"], "type": "store cupboard" },
    { "food": "Kidney beans", "nutrients": ["iron-rich", "protein"], "type": "store cupboard" },
    { "food": "Quinoa", "nutrients": ["protein", "magnesium"], "type": "store cupboard" },
    { "food": "Pumpkin seeds", "nutrients": ["zinc", "magnesium"], "type": "store cupboard" },
    { "food": "Sunflower seeds", "nutrients": ["vitamin E", "healthy fats"], "type": "store cupboard" },
    { "food": "Lean red meat", "nutrients": ["iron-rich", "protein"], "type": "fresh" },
    { "food": "Salmon", "nutrients": ["omega-3", "protein"], "type": "fresh" },
    { "food": "Sardines", "nutrients": ["omega-3", "calcium"], "type": "store cupboard" },
    { "food": "Eggs", "nutrients": ["protein", "vitamin B12"], "type": "fresh" },
    { "food": "Dark chocolate (70%+)", "nutrients": ["magnesium", "antioxidants"], "type": "store cupboard" },
    { "food": "Oranges", "nutrients": ["vitamin C"], "type": "fresh" },
    { "food": "Strawberries", "nutrients": ["vitamin C", "antioxidants"], "type": "fresh" },
    { "food": "Blueberries", "nutrients": ["antioxidants"], "type": "fresh" },
    { "food": "Watermelon", "nutrients": ["hydration", "vitamin C"], "type": "fresh" },
    { "food": "Ginger", "nutrients": ["anti-inflammatory"], "type": "fresh" },
    { "food": "Turmeric", "nutrients": ["anti-inflammatory"], "type": "store cupboard" },
    { "food": "Chamomile tea", "nutrients": ["calming"], "type": "store cupboard" },
    { "food": "Peppermint tea", "nutrients": ["digestive support"], "type": "store cupboard" },
    { "food": "Oats", "nutrients": ["fiber", "magnesium"], "type": "store cupboard" },
    { "food": "Brown rice", "nutrients": ["fiber", "B vitamins"], "type": "store cupboard" },
    { "food": "Sweet potatoes", "nutrients": ["beta-carotene", "fiber"], "type": "fresh" },
    { "food": "Avocado", "nutrients": ["healthy fats", "potassium"], "type": "fresh" },
    { "food": "Olive oil", "nutrients": ["healthy fats"], "type": "store cupboard" },
    { "food": "Walnuts", "nutrients": ["omega-3", "magnesium"], "type": "store cupboard" },
    { "food": "Almonds", "nutrients": ["vitamin E", "magnesium"], "type": "store cupboard" },
    { "food": "Greek yogurt", "nutrients": ["protein", "probiotics"], "type": "fresh" }
  ],
  "FollicularPhase": [
    { "food": "Asparagus", "nutrients": ["vitamin K", "folate"], "type": "fresh" },
    { "food": "Zucchini", "nutrients": ["fiber", "vitamin C"], "type": "fresh" },
    { "food": "Bell peppers", "nutrients": ["vitamin C", "antioxidants"], "type": "fresh" },
    { "food": "Carrots", "nutrients": ["beta-carotene", "vitamin A"], "type": "fresh" },
    { "food": "Beets", "nutrients": ["nitrates", "antioxidants"], "type": "fresh" },
    { "food": "Apples", "nutrients": ["fiber", "vitamin C"], "type": "fresh" },
    { "food": "Pears", "nutrients": ["fiber"], "type": "fresh" },
    { "food": "Grapes", "nutrients": ["antioxidants"], "type": "fresh" },
    { "food": "Mango", "nutrients": ["vitamin A", "vitamin C"], "type": "fresh" },
    { "food": "Pineapple", "nutrients": ["vitamin C", "bromelain"], "type": "fresh" },
    { "food": "Chia seeds", "nutrients": ["omega-3", "fiber"], "type": "store cupboard" },
    { "food": "Flaxseeds", "nutrients": ["omega-3", "fiber"], "type": "store cupboard" },
    { "food": "Hemp seeds", "nutrients": ["protein", "omega-3"], "type": "store cupboard" },
    { "food": "Chicken breast", "nutrients": ["protein"], "type": "fresh" },
    { "food": "Turkey", "nutrients": ["protein"], "type": "fresh" },
    { "food": "Cod", "nutrients": ["protein", "omega-3"], "type": "fresh" },
    { "food": "Tuna", "nutrients": ["protein", "omega-3"], "type": "store cupboard" },
    { "food": "Eggs", "nutrients": ["protein", "vitamin B12"], "type": "fresh" },
    { "food": "Edamame", "nutrients": ["protein", "fiber"], "type": "fresh" },
    { "food": "Tofu", "nutrients": ["protein", "calcium"], "type": "fresh" },
    { "food": "Tempeh", "nutrients": ["protein", "probiotics"], "type": "fresh" },
    { "food": "Brown rice", "nutrients": ["fiber", "B vitamins"], "type": "store cupboard" },
    { "food": "Buckwheat", "nutrients": ["fiber", "magnesium"], "type": "store cupboard" },
    { "food": "Millet", "nutrients": ["fiber", "magnesium"], "type": "store cupboard" },
    { "food": "Lentils", "nutrients": ["protein", "iron"], "type": "store cupboard" },
    { "food": "Hummus", "nutrients": ["protein", "fiber"], "type": "store cupboard" },
    { "food": "Olive oil", "nutrients": ["healthy fats"], "type": "store cupboard" },
    { "food": "Cashews", "nutrients": ["magnesium", "healthy fats"], "type": "store cupboard" },
    { "food": "Pistachios", "nutrients": ["protein", "vitamin B6"], "type": "store cupboard" },
    { "food": "Kefir", "nutrients": ["probiotics", "protein"], "type": "fresh" }
  ],
  "OvulatoryPhase": [
    { "food": "Spinach", "nutrients": ["iron-rich", "magnesium"], "type": "fresh" },
    { "food": "Arugula", "nutrients": ["vitamin K", "antioxidants"], "type": "fresh" },
    { "food": "Brussels sprouts", "nutrients": ["fiber", "vitamin C"], "type": "fresh" },
    { "food": "Cauliflower", "nutrients": ["fiber", "vitamin C"], "type": "fresh" },
    { "food": "Tomatoes", "nutrients": ["lycopene", "vitamin C"], "type": "fresh" },
    { "food": "Berries (raspberries, blueberries, blackberries)", "nutrients": ["antioxidants", "vitamin C"], "type": "fresh" },
    { "food": "Citrus fruits (lemon, lime, orange)", "nutrients": ["vitamin C"], "type": "fresh" },
    { "food": "Pomegranate", "nutrients": ["antioxidants", "vitamin C"], "type": "fresh" },
    { "food": "Grapes", "nutrients": ["antioxidants"], "type": "fresh" },
    { "food": "Garlic", "nutrients": ["anti-inflammatory", "immune support"], "type": "store cupboard" },
    { "food": "Onion", "nutrients": ["antioxidants", "immune support"], "type": "fresh" },
    { "food": "Ginger", "nutrients": ["anti-inflammatory"], "type": "fresh" },
    { "food": "Turmeric", "nutrients": ["anti-inflammatory"], "type": "store cupboard" },
    { "food": "Salmon", "nutrients": ["omega-3", "protein"], "type": "fresh" },
    { "food": "Sardines", "nutrients": ["omega-3", "calcium"], "type": "store cupboard" },
    { "food": "Shrimp", "nutrients": ["protein", "selenium"], "type": "fresh" },
    { "food": "Eggs", "nutrients": ["protein", "vitamin B12"], "type": "fresh" },
    { "food": "Chickpeas", "nutrients": ["protein", "fiber"], "type": "store cupboard" },
    { "food": "Lentils", "nutrients": ["protein", "iron"], "type": "store cupboard" },
    { "food": "Quinoa", "nutrients": ["protein", "magnesium"], "type": "store cupboard" },
    { "food": "Brown rice", "nutrients": ["fiber", "B vitamins"], "type": "store cupboard" },
    { "food": "Oats", "nutrients": ["fiber", "magnesium"], "type": "store cupboard" },
    { "food": "Avocado", "nutrients": ["healthy fats", "potassium"], "type": "fresh" },
    { "food": "Olive oil", "nutrients": ["healthy fats"], "type": "store cupboard" },
    { "food": "Walnuts", "nutrients": ["omega-3", "magnesium"], "type": "store cupboard" },
    { "food": "Almonds", "nutrients": ["vitamin E", "magnesium"], "type": "store cupboard" },
    { "food": "Brazil nuts", "nutrients": ["selenium", "healthy fats"], "type": "store cupboard" },
    { "food": "Dark chocolate", "nutrients": ["magnesium", "antioxidants"], "type": "store cupboard" },
    { "food": "Green tea", "nutrients": ["antioxidants", "calming"], "type": "store cupboard" },
    { "food": "Matcha", "nutrients": ["antioxidants", "L-theanine"], "type": "store cupboard" }
  ],
  "LutealPhase": [
    { "food": "Kale", "nutrients": ["iron-rich", "vitamin K"], "type": "fresh" },
    { "food": "Spinach", "nutrients": ["iron-rich", "magnesium"], "type": "fresh" },
    { "food": "Swiss chard", "nutrients": ["magnesium", "vitamin K"], "type": "fresh" },
    { "food": "Broccoli", "nutrients": ["vitamin C", "fiber"], "type": "fresh" },
    { "food": "Sweet potatoes", "nutrients": ["beta-carotene", "fiber"], "type": "fresh" },
    { "food": "Carrots", "nutrients": ["beta-carotene", "vitamin A"], "type": "fresh" },
    { "food": "Pumpkin", "nutrients": ["beta-carotene", "fiber"], "type": "fresh" },
    { "food": "Bananas", "nutrients": ["potassium", "vitamin B6"], "type": "fresh" },
    { "food": "Apples", "nutrients": ["fiber", "vitamin C"], "type": "fresh" },
    { "food": "Pears", "nutrients": ["fiber"], "type": "fresh" },
    { "food": "Berries", "nutrients": ["antioxidants", "vitamin C"], "type": "fresh" },
    { "food": "Dates", "nutrients": ["iron", "fiber"], "type": "store cupboard" },
    { "food": "Figs", "nutrients": ["fiber", "calcium"], "type": "store cupboard" },
    { "food": "Chickpeas", "nutrients": ["protein", "fiber"], "type": "store cupboard" },
    { "food": "Lentils", "nutrients": ["protein", "iron"], "type": "store cupboard" },
    { "food": "Black beans", "nutrients": ["protein", "fiber"], "type": "store cupboard" },
    { "food": "Brown rice", "nutrients": ["fiber", "B vitamins"], "type": "store cupboard" },
    { "food": "Quinoa", "nutrients": ["protein", "magnesium"], "type": "store cupboard" },
    { "food": "Oats", "nutrients": ["fiber", "magnesium"], "type": "store cupboard" },
    { "food": "Salmon", "nutrients": ["omega-3", "protein"], "type": "fresh" },
    { "food": "Mackerel", "nutrients": ["omega-3", "vitamin D"], "type": "fresh" },
    { "food": "Turkey", "nutrients": ["protein", "tryptophan"], "type": "fresh" },
    { "food": "Eggs", "nutrients": ["protein", "vitamin B12"], "type": "fresh" },
    { "food": "Avocado", "nutrients": ["healthy fats", "potassium"], "type": "fresh" },
    { "food": "Olive oil", "nutrients": ["healthy fats"], "type": "store cupboard" },
    { "food": "Walnuts", "nutrients": ["omega-3", "magnesium"], "type": "store cupboard" },
    { "food": "Almonds", "nutrients": ["vitamin E", "magnesium"], "type": "store cupboard" },
    { "food": "Cashews", "nutrients": ["magnesium", "healthy fats"], "type": "store cupboard" },
    { "food": "Dark chocolate", "nutrients": ["magnesium", "antioxidants"], "type": "store cupboard" },
    { "food": "Chamomile tea", "nutrients": ["calming", "anti-inflammatory"], "type": "store cupboard" }
  ]
}
