wellBeing = {
  "WellbeingActivities": [
    { "activity": "Restorative yoga", "phases": ["Menstrual", "Luteal"], "description": "Gentle poses to release tension and promote relaxation.", "emoji": "🧘‍♀️", "link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3193654/" },
    { "activity": "Journaling for emotional release", "phases": ["Menstrual", "Luteal"], "description": "Write down thoughts and feelings to process emotions.", "emoji": "📓", "link": "https://positivepsychology.com/benefits-of-journaling/" },
    { "activity": "Warm baths with Epsom salts", "phases": ["Menstrual", "Luteal"], "description": "Soothing soak to ease cramps and relax muscles.", "emoji": "🛁", "link": "https://www.healthline.com/health/epsom-salt-bath" },
    { "activity": "Meditation or breathwork", "phases": ["Menstrual", "Luteal", "Ovulatory"], "description": "Mindful breathing to calm the mind and reduce stress.", "emoji": "🧘", "link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6145066/" },
    { "activity": "Gentle stretching", "phases": ["Menstrual", "Luteal"], "description": "Light stretches to improve circulation and flexibility.", "emoji": "🤸‍♀️", "link": "https://www.health.harvard.edu/staying-healthy/the-importance-of-stretching" },
    { "activity": "Herbal teas (chamomile, peppermint)", "phases": ["Menstrual", "Luteal"], "description": "Warm, soothing teas to ease digestion and promote calm.", "emoji": "🍵", "link": "https://www.healthline.com/nutrition/10-herbal-teas" },
    { "activity": "Listening to calming music", "phases": ["Menstrual", "Luteal"], "description": "Soft tunes to relax the nervous system.", "emoji": "🎶", "link": "https://pubmed.ncbi.nlm.nih.gov/32204763/" },
    { "activity": "Aromatherapy (lavender, rose)", "phases": ["Menstrual", "Luteal"], "description": "Essential oils to reduce stress and uplift mood.", "emoji": "🌸", "link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6007527/" },
    { "activity": "Cozy reading time", "phases": ["Menstrual", "Luteal"], "description": "Curl up with a book for comfort and escape.", "emoji": "📚", "link": "https://www.scottishbooktrust.com/articles/mental-health-and-the-benefits-of-reading" },
    { "activity": "Slow walks in nature", "phases": ["Menstrual", "Follicular", "Luteal"], "description": "Gentle outdoor strolls to connect with nature.", "emoji": "🌳", "link": "https://www.frontiersin.org/articles/10.3389/fpsyg.2020.00578/full" },

    { "activity": "Dance workouts", "phases": ["Follicular", "Ovulatory"], "description": "Fun, energizing movement to boost mood and fitness.", "emoji": "💃", "link": "https://www.sydney.edu.au/news-opinion/news/2024/02/12/dancing-may-be-better-than-other-exercise-for-improving-mental-h.html" },
    { "activity": "Strength training (light weights)", "phases": ["Follicular"], "description": "Build strength and energy with manageable resistance.", "emoji": "🏋️‍♀️", "link": "https://www.loseit.com/articles/can-you-build-muscle-with-light-weights/" },
    { "activity": "Trying a new hobby or skill", "phases": ["Follicular"], "description": "Explore creativity and stimulate the brain.", "emoji": "🎨", "link": "https://www.nhsinform.scot/healthy-living/mental-wellbeing/improve-mental-wellbeing-by-learning-new-things/" },
    { "activity": "Brainstorming/vision boarding", "phases": ["Follicular"], "description": "Map out ideas and visualize future goals.", "emoji": "🖼️", "link": "https://therapytips.org/advice/the-psychology-behind-making-vision-boards-work" },
    { "activity": "Social outings with friends", "phases": ["Follicular", "Ovulatory"], "description": "Connect socially to boost oxytocin and joy.", "emoji": "🥂", "link": "https://www.nhsinform.scot/healthy-living/mental-wellbeing/social-connections-for-mental-wellbeing/" },
    { "activity": "Outdoor cycling or jogging", "phases": ["Follicular"], "description": "Cardio exercise to harness rising energy.", "emoji": "🚴‍♀️", "link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1470658/" },
    { "activity": "Creative writing", "phases": ["Follicular", "Menstrual"], "description": "Expressive writing to channel creativity and emotions.", "emoji": "✍️", "link": "https://positivepsychology.com/expressive-writing/" },
    { "activity": "Cooking new recipes", "phases": ["Follicular", "Luteal"], "description": "Experiment with meals to spark creativity.", "emoji": "🍳", "link": "https://www.psychologytoday.com/us/blog/urban-survival/201911/cooking-and-mental-health" },
    { "activity": "Planning projects", "phases": ["Follicular"], "description": "Organize and set goals during high focus.", "emoji": "🗒️", "link": "https://www.apa.org/monitor/2019/01/cover-projects" },
    { "activity": "Morning affirmations", "phases": ["Follicular"], "description": "Positive self-talk to boost confidence.", "emoji": "🌞", "link": "https://www.psychologytoday.com/us/blog/the-path-passionate-happiness/201812/the-power-affirmations" },

    { "activity": "High-intensity interval training (HIIT)", "phases": ["Ovulatory"], "description": "Short bursts of intense exercise to match peak energy.", "emoji": "⚡", "link": "https://www.mdpi.com/2308-3425/12/4/158" },
    { "activity": "Group fitness classes", "phases": ["Ovulatory"], "description": "Social workouts to combine energy and connection.", "emoji": "👯‍♀️", "link": "https://www.psychologytoday.com/us/blog/urban-survival/201911/group-exercise-and-mental-health" },
    { "activity": "Networking events", "phases": ["Ovulatory"], "description": "Leverage confidence and communication skills socially.", "emoji": "🤝", "link": "https://www.enlivened.co.uk/confidence-wellbeing-conference-2025.html" },
    { "activity": "Public speaking practice", "phases": ["Ovulatory"], "description": "Harness peak confidence to practice communication.", "emoji": "🎤", "link": "https://www.apa.org/gradpsych/2011/11/public-speaking" },
    { "activity": "Date nights or social dinners", "phases": ["Ovulatory"], "description": "Enjoy connection and intimacy during peak energy.", "emoji": "🍷", "link": "https://www.achievecommunities.org/the-impact-of-social-connections-on-mental-health-building-relationships-for-well-being/" },
    { "activity": "Creative collaborations", "phases": ["Ovulatory", "Follicular"], "description": "Work with others to spark innovation.", "emoji": "🤝", "link": "https://www.frontiersin.org/articles/10.3389/fpsyg.2019.00710/full" },
    { "activity": "Singing or performing arts", "phases": ["Ovulatory"], "description": "Expressive arts to channel confidence.", "emoji": "🎤", "link": "https://www.frontiersin.org/articles/10.3389/fpsyg.2019.00710/full" },
    { "activity": "Outdoor adventures (hiking, kayaking)", "phases": ["Ovulatory", "Follicular"], "description": "Active exploration to harness vitality.", "emoji": "⛰️", "link": "https://www.tandfonline.com/doi/pdf/10.1080/14729679.2023.2220836" },
    { "activity": "Volunteering/community service", "phases": ["Ovulatory"], "description": "Give back and connect socially.", "emoji": "🤲", "link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5508927/" }
  ]
}